//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LMS1Entities1 : DbContext
    {
        public LMS1Entities1()
            : base("name=LMS1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Admin_Registration> Tbl_Admin_Registration { get; set; }
        public virtual DbSet<Tbl_AllRegistration> Tbl_AllRegistration { get; set; }
        public virtual DbSet<Tbl_Course> Tbl_Course { get; set; }
        public virtual DbSet<Tbl_Course_Category> Tbl_Course_Category { get; set; }
        public virtual DbSet<Tbl_Course_Details> Tbl_Course_Details { get; set; }
        public virtual DbSet<Tbl_Course_Payment> Tbl_Course_Payment { get; set; }
        public virtual DbSet<Tbl_Course_Quiz_Que> Tbl_Course_Quiz_Que { get; set; }
        public virtual DbSet<Tbl_Course_Registraion> Tbl_Course_Registraion { get; set; }
        public virtual DbSet<Tbl_Faculty_Course> Tbl_Faculty_Course { get; set; }
        public virtual DbSet<Tbl_Faculty_Registration> Tbl_Faculty_Registration { get; set; }
        public virtual DbSet<Tbl_Feedback_Ans> Tbl_Feedback_Ans { get; set; }
        public virtual DbSet<Tbl_Feedback_Que> Tbl_Feedback_Que { get; set; }
        public virtual DbSet<Tbl_Student_Quiz_Result> Tbl_Student_Quiz_Result { get; set; }
        public virtual DbSet<Tbl_Student_Registration> Tbl_Student_Registration { get; set; }
    
        public virtual ObjectResult<string> GetAdminForgotPassword(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetAdminForgotPassword", userNameParameter);
        }
    
        public virtual ObjectResult<string> GetAdminLoginInfo(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetAdminLoginInfo", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> GetFacultyForgotPassword(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetFacultyForgotPassword", userNameParameter);
        }
    
        public virtual ObjectResult<string> GetFacultyLoginInfo(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetFacultyLoginInfo", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<string> GetStudentForgotPassword(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetStudentForgotPassword", userNameParameter);
        }
    
        public virtual ObjectResult<string> GetStudentLoginInfo(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetStudentLoginInfo", userNameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<SP_GetAdmin_Result> SP_GetAdmin(Nullable<int> pKAdminID)
        {
            var pKAdminIDParameter = pKAdminID.HasValue ?
                new ObjectParameter("PKAdminID", pKAdminID) :
                new ObjectParameter("PKAdminID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetAdmin_Result>("SP_GetAdmin", pKAdminIDParameter);
        }
    
        public virtual ObjectResult<SP_GetAllFaculty_Result> SP_GetAllFaculty()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetAllFaculty_Result>("SP_GetAllFaculty");
        }
    
        public virtual ObjectResult<SP_GetSingleFaculty_Result> SP_GetSingleFaculty(Nullable<int> pKFacultyRegID)
        {
            var pKFacultyRegIDParameter = pKFacultyRegID.HasValue ?
                new ObjectParameter("PKFacultyRegID", pKFacultyRegID) :
                new ObjectParameter("PKFacultyRegID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetSingleFaculty_Result>("SP_GetSingleFaculty", pKFacultyRegIDParameter);
        }
    
        public virtual ObjectResult<SP_GetSingleStudent_Result> SP_GetSingleStudent(Nullable<int> pKStudentRegID)
        {
            var pKStudentRegIDParameter = pKStudentRegID.HasValue ?
                new ObjectParameter("PKStudentRegID", pKStudentRegID) :
                new ObjectParameter("PKStudentRegID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetSingleStudent_Result>("SP_GetSingleStudent", pKStudentRegIDParameter);
        }
    
        public virtual int SP_InsertTbl_Admin_Registration(string firstName, string middleName, string lastName, string emailID, string password, string role, Nullable<System.DateTime> dOB, string gender)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertTbl_Admin_Registration", firstNameParameter, middleNameParameter, lastNameParameter, emailIDParameter, passwordParameter, roleParameter, dOBParameter, genderParameter);
        }
    
        public virtual int SP_InsertTbl_AllRegistration(string emailID, string role)
        {
            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertTbl_AllRegistration", emailIDParameter, roleParameter);
        }
    
        public virtual int SP_InsertTbl_Faculty_Registration(string firstName, string middleName, string lastName, string emailID, string password, string contactNo, string alternateContactNo, string address, string skills, Nullable<System.DateTime> dOB, string gender)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var contactNoParameter = contactNo != null ?
                new ObjectParameter("ContactNo", contactNo) :
                new ObjectParameter("ContactNo", typeof(string));
    
            var alternateContactNoParameter = alternateContactNo != null ?
                new ObjectParameter("AlternateContactNo", alternateContactNo) :
                new ObjectParameter("AlternateContactNo", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var skillsParameter = skills != null ?
                new ObjectParameter("Skills", skills) :
                new ObjectParameter("Skills", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertTbl_Faculty_Registration", firstNameParameter, middleNameParameter, lastNameParameter, emailIDParameter, passwordParameter, contactNoParameter, alternateContactNoParameter, addressParameter, skillsParameter, dOBParameter, genderParameter);
        }
    
        public virtual int SP_InsertTbl_Student_Registration(string firstName, string middleName, string lastName, string emailID, string password, string contactNo, string alternateContactNo, string address, Nullable<System.DateTime> dOB, string gender)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var contactNoParameter = contactNo != null ?
                new ObjectParameter("ContactNo", contactNo) :
                new ObjectParameter("ContactNo", typeof(string));
    
            var alternateContactNoParameter = alternateContactNo != null ?
                new ObjectParameter("AlternateContactNo", alternateContactNo) :
                new ObjectParameter("AlternateContactNo", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_InsertTbl_Student_Registration", firstNameParameter, middleNameParameter, lastNameParameter, emailIDParameter, passwordParameter, contactNoParameter, alternateContactNoParameter, addressParameter, dOBParameter, genderParameter);
        }
    
        public virtual int SP_UpdateAdminPassword(string emailID, string password)
        {
            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateAdminPassword", emailIDParameter, passwordParameter);
        }
    
        public virtual int SP_UpdateFacultyPassword(string emailID, string password)
        {
            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateFacultyPassword", emailIDParameter, passwordParameter);
        }
    
        public virtual int SP_UpdateStudentPassword(string emailID, string password)
        {
            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateStudentPassword", emailIDParameter, passwordParameter);
        }
    
        public virtual int SP_UpdateTbl_Admin_Registration(Nullable<int> pKAdminID, string firstName, string middleName, string lastName, string emailID, string role, Nullable<System.DateTime> dOB, string gender)
        {
            var pKAdminIDParameter = pKAdminID.HasValue ?
                new ObjectParameter("PKAdminID", pKAdminID) :
                new ObjectParameter("PKAdminID", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));
    
            var roleParameter = role != null ?
                new ObjectParameter("Role", role) :
                new ObjectParameter("Role", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateTbl_Admin_Registration", pKAdminIDParameter, firstNameParameter, middleNameParameter, lastNameParameter, emailIDParameter, roleParameter, dOBParameter, genderParameter);
        }
    
        public virtual int SP_UpdateTbl_Faculty_Registration(Nullable<int> pKFacultyRegID, string firstName, string middleName, string lastName, string emailID, string contactNo, string alternateContactNo, string address, string skills, Nullable<System.DateTime> dOB, string gender, Nullable<int> modifiedBy)
        {
            var pKFacultyRegIDParameter = pKFacultyRegID.HasValue ?
                new ObjectParameter("PKFacultyRegID", pKFacultyRegID) :
                new ObjectParameter("PKFacultyRegID", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));
    
            var contactNoParameter = contactNo != null ?
                new ObjectParameter("ContactNo", contactNo) :
                new ObjectParameter("ContactNo", typeof(string));
    
            var alternateContactNoParameter = alternateContactNo != null ?
                new ObjectParameter("AlternateContactNo", alternateContactNo) :
                new ObjectParameter("AlternateContactNo", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var skillsParameter = skills != null ?
                new ObjectParameter("Skills", skills) :
                new ObjectParameter("Skills", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateTbl_Faculty_Registration", pKFacultyRegIDParameter, firstNameParameter, middleNameParameter, lastNameParameter, emailIDParameter, contactNoParameter, alternateContactNoParameter, addressParameter, skillsParameter, dOBParameter, genderParameter, modifiedByParameter);
        }
    
        public virtual int SP_UpdateTbl_Student_Registration(Nullable<int> pKStudentRegID, string firstName, string middleName, string lastName, string emailID, string contactNo, string alternateContactNo, string address, Nullable<System.DateTime> dOB, string gender, Nullable<int> modifiedBy)
        {
            var pKStudentRegIDParameter = pKStudentRegID.HasValue ?
                new ObjectParameter("PKStudentRegID", pKStudentRegID) :
                new ObjectParameter("PKStudentRegID", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));
    
            var contactNoParameter = contactNo != null ?
                new ObjectParameter("ContactNo", contactNo) :
                new ObjectParameter("ContactNo", typeof(string));
    
            var alternateContactNoParameter = alternateContactNo != null ?
                new ObjectParameter("AlternateContactNo", alternateContactNo) :
                new ObjectParameter("AlternateContactNo", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var modifiedByParameter = modifiedBy.HasValue ?
                new ObjectParameter("ModifiedBy", modifiedBy) :
                new ObjectParameter("ModifiedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UpdateTbl_Student_Registration", pKStudentRegIDParameter, firstNameParameter, middleNameParameter, lastNameParameter, emailIDParameter, contactNoParameter, alternateContactNoParameter, addressParameter, dOBParameter, genderParameter, modifiedByParameter);
        }
    }
}
