//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Feedback_Ans
    {
        public int PKFeedbackAnsID { get; set; }
        public Nullable<int> FKFeedbackQueID { get; set; }
        public string Answer { get; set; }
        public Nullable<int> FKStudentRegID { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
    
        public virtual Tbl_Feedback_Que Tbl_Feedback_Que { get; set; }
        public virtual Tbl_Student_Registration Tbl_Student_Registration { get; set; }
    }
}
