//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Admin_Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Admin_Registration()
        {
            this.Tbl_Course_Category = new HashSet<Tbl_Course_Category>();
            this.Tbl_Faculty_Course = new HashSet<Tbl_Faculty_Course>();
        }
    
        public int PKAdminID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Status { get; set; }
        public Nullable<int> LoginFailedCount { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string MiddleName { get; set; }
    
        public virtual Tbl_Admin_Registration Tbl_Admin_Registration1 { get; set; }
        public virtual Tbl_Admin_Registration Tbl_Admin_Registration2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Course_Category> Tbl_Course_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Faculty_Course> Tbl_Faculty_Course { get; set; }
    }
}
