//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Course_Registraion
    {
        public int PKCourseRegID { get; set; }
        public Nullable<int> FKCourseID { get; set; }
        public Nullable<int> FKStudentRegID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    
        public virtual Tbl_Course Tbl_Course { get; set; }
        public virtual Tbl_Student_Registration Tbl_Student_Registration { get; set; }
    }
}
